<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Vrushabh-PC" ignored="0" name="Test2" tests="1" failures="0" timestamp="08 Jul 2017 06:11:31 GMT" time="0.078" errors="0">
  <testcase name="@BeforeTest beforeTest" time="0.016" classname="com.project.SecondProject.TrackoMainTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.project.SecondProject.TrackoMainTest.beforeTest(TrackoMainTest.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeTest beforeTest -->
  <testcase name="@AfterTest afterTest" time="0.0" classname="com.project.SecondProject.TrackoMainTest">
    <skipped/>
  </testcase> <!-- @AfterTest afterTest -->
  <testcase name="f" time="0.0" classname="com.project.SecondProject.TrackoMainTest">
    <skipped/>
  </testcase> <!-- f -->
</testsuite> <!-- Test2 -->
